CREATE TABLE IF NOT EXISTS "activities" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "occurs_at" TIMESTAMPTZ NOT NULL,
  "location_name" TEXT NOT NULL,
  "location_address" TEXT,
  "location_url" TEXT,
  "facebook_url" TEXT
);

CREATE TABLE IF NOT EXISTS "config" (
  "config_key" TEXT PRIMARY KEY NOT NULL,
  "config_value" JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS "email_jobs" (
  "id" UUID PRIMARY KEY NOT NULL DEFAULT (gen_random_uuid()),
  "job_type" TEXT NOT NULL,
  "payload" JSONB NOT NULL,
  "recipient" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT ('pending'::text),
  "retries" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "krambambouli_customers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INTEGER,
  "first_name" TEXT NOT NULL,
  "last_name" TEXT NOT NULL,
  "email" TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "krambambouli_delivery_locations" (
  "order_id" UUID PRIMARY KEY NOT NULL,
  "street_name" TEXT NOT NULL,
  "house_number" TEXT NOT NULL,
  "bus" TEXT,
  "postal_code" TEXT NOT NULL,
  "city" TEXT
);

CREATE TABLE IF NOT EXISTS "krambambouli_delivery_zones" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "postal_code_from" INTEGER NOT NULL,
  "postal_code_to" INTEGER NOT NULL,
  "price" INTEGER NOT NULL,
  "active" BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS "krambambouli_order_items" (
  "order_id" UUID NOT NULL,
  "product_id" INTEGER NOT NULL,
  "amount" INTEGER NOT NULL,
  PRIMARY KEY ("order_id", "product_id")
);

CREATE TABLE IF NOT EXISTS "krambambouli_orders" (
  "id" UUID PRIMARY KEY NOT NULL DEFAULT (gen_random_uuid()),
  "order_number" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "customer_id" INTEGER,
  "delivery_option" TEXT NOT NULL,
  "pickup_location" INTEGER,
  "total_owed" INTEGER DEFAULT 0,
  "paid" BOOLEAN NOT NULL DEFAULT false,
  "received" BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS "krambambouli_pickup_locations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "active" BOOLEAN NOT NULL,
  "manager_id" INTEGER
);

CREATE TABLE IF NOT EXISTS "products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "category" TEXT,
  "image_url" TEXT,
  "price" INTEGER NOT NULL DEFAULT 0,
  "active" BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS "permissions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "slug" TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "role_permissions" (
  "role_id" INTEGER NOT NULL,
  "permission_id" INTEGER NOT NULL,
  PRIMARY KEY ("role_id", "permission_id")
);

CREATE TABLE IF NOT EXISTS "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" TEXT UNIQUE NOT NULL,
  "password" TEXT NOT NULL,
  "first_name" TEXT NOT NULL,
  "last_name" TEXT NOT NULL DEFAULT '',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "user_roles" (
  "user_id" INTEGER NOT NULL,
  "role_id" INTEGER NOT NULL,
  PRIMARY KEY ("user_id", "role_id")
);

CREATE TABLE IF NOT EXISTS "password_recovery_tokens" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INTEGER NOT NULL,
  "token_hash" char(64) NOT NULL,
  "created_at" TIMESTAMPTZ DEFAULT (now()),
  "expires_at" TIMESTAMPTZ NOT NULL,
  "used_at" TIMESTAMPTZ,
  "request_ip" INET
);

CREATE INDEX "idx_krambambouli_orders_order_number" ON "krambambouli_orders" USING BTREE ("order_number");

CREATE INDEX "idx_krambambouli_orders_id" ON "krambambouli_orders" USING BTREE ("id");

CREATE INDEX "idx_roles_name" ON "roles" USING BTREE ("name");

CREATE INDEX "idx_users_email" ON "users" USING BTREE ("email");

ALTER TABLE "krambambouli_customers" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "krambambouli_pickup_locations" ADD FOREIGN KEY ("manager_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "password_recovery_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "krambambouli_orders" ADD CONSTRAINT "fk_customer" FOREIGN KEY ("customer_id") REFERENCES "krambambouli_customers" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "krambambouli_delivery_locations" ADD CONSTRAINT "fk_order" FOREIGN KEY ("order_id") REFERENCES "krambambouli_orders" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "krambambouli_order_items" ADD CONSTRAINT "fk_order" FOREIGN KEY ("order_id") REFERENCES "krambambouli_orders" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "krambambouli_order_items" ADD CONSTRAINT "fk_product" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "role_permissions" ADD CONSTRAINT "fk_role_permissions_role" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "role_permissions" ADD CONSTRAINT "fk_role_permissions_perm" FOREIGN KEY ("permission_id") REFERENCES "permissions" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_roles" ADD CONSTRAINT "fk_user_roles_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_roles" ADD CONSTRAINT "fk_user_roles_role" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "krambambouli_orders" ADD CONSTRAINT "fk_pickup_location" FOREIGN KEY ("pickup_location") REFERENCES "krambambouli_pickup_locations" ("id") DEFERRABLE INITIALLY IMMEDIATE;
