name: Deploy website to railway

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Use Node latest lts
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up --service ${{ secrets.SERVICE_NAME }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
