name: Deploy website to railway

on:
  workflow_run:
    workflows: ["Build Docker image"]
    branches:
      - main
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: production
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: Install Railway CLI
        run: |
          bash <(curl -fsSL railway.com/install.sh) -y
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      - name: Deploy to Railway
        run: railway up --ci --service ${{ secrets.SERVICE_NAME }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
